name: Run lambroll deploy
description: Run lambroll deploy command.
inputs:
  dir:
    description: "Working directory for lambroll"
    required: true
  function_names:
    description: "Names of the lambda function"
    required: true
  lambroll_alias:
    description: "Alias of the lambda function"
    required: true
  lambroll_envfile:
    description: "Environment file for lambroll"
    required: true
  lambroll_keep_versions:
    description: "Keep version quantity of the lambda function"
    default: "5"
  tfstate_url:
    description: "URL of the tfstate file"
    required: true
  version:
    description: "Version of lambroll"
    default: "v0.14.2"
    required: false
runs:
  using: "composite"
  steps:
    - name: Install lambroll
      uses: fujiwara/lambroll@v0
      with:
        version: ${{ inputs.version }}
    - name: Run lambroll deploy
      working-directory: ${{ inputs.dir }}
      shell: bash
      env:
        ALIAS: ${{ inputs.lambroll_alias }}
        ENVFILE: ${{ inputs.lambroll_envfile }}
        QUANTITY: ${{ inputs.lambroll_keep_versions }}
        TFSTATE: ${{ inputs.tfstate_url }}
      run: |
        for i in ${{ inputs.function_names }}
        do
          lambroll deploy --function $i.json --alias=$ALIAS --keep-versions=$QUANTITY --envfile=$ENVFILE --tfstate=$TFSTATE
        done
