name: "Install terraform, then run terraform apply"
description: |
  Terraform をインストールし、 terraform apply を実行します。
inputs:
  args_apply:
    description: "Arguments for terraform apply"
    default: ""
  args_init:
    description: "Arguments for terraform init"
    default: ""
  aws_region:
    description: "The AWS region"
    default: "ap-northeast-1"
  aws_role:
    description: "The AWS role ARN"
    default: ""
  dir:
    description: "Working directory for terraform"
  need_tfcmt:
    description: "If true, install tfcmt"
    default: "false"
  token:
    description: "GitHub token, required if need_tfcmt is true"
  version_tfcmt:
    description: "Version of tfcmt"
    default: "v4.9.0"
runs:
  using: composite
  steps:
    - uses: ./.github/actions/commons/terraform_install
      with:
        args_init: ${{ inputs.args_init }}
        aws_region: ${{ inputs.aws_region }}
        aws_role: ${{ inputs.aws_role }}
        dir: ${{ inputs.dir }}
        need_tfcmt: ${{ inputs.need_tfcmt }}
        version_tfcmt: ${{ inputs.version_tfcmt }}
    - uses: ./.github/actions/commons/terraform_apply
      with:
        args_apply: ${{ inputs.args_apply }}
        dir: ${{ inputs.dir }}
        need_tfcmt: ${{ inputs.need_tfcmt }}
        token: ${{ inputs.token }}
