name: "Run black and flake8"
description: |
  Poetry を使用して black/flake8 をインストールし、コードの静的解析を行います。
inputs:
  dir:
    description: "Working directory for installation"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: poetry add --dev black flake8
      shell: bash
      working-directory: ${{ inputs.dir }}
    - name: Check by black
      run: poetry run black --check --line-length=119 backend
      working-directory: ${{ inputs.dir }}
      shell: bash
    - name: poetry run Check by flake8
      run: poetry run flake8 --ignore=E203,W293,W503,W504 --max-line-length=119 backend
      working-directory: ${{ inputs.dir }}
      shell: bash
