name: "Install Python runtime, then run lint task"
description: |
  Python をインストールし、 lint タスクを実行します。
inputs:
  dir:
    description: "Working directory for installation"
    required: true
  version:
    description: "Python version"
    default: "3.11"
  version_poetry:
    description: "Poetry version"
    default: "1.8.2"
runs:
  using: composite
  steps:
    - uses: ./.github/actions/commons/python_install
      with:
        dir: ${{ inputs.dir }}
        version: ${{ inputs.version }}
        version_poetry: ${{ inputs.version_poetry }}
    - uses: ./.github/actions/commons/python_lint
      with:
        dir: ${{ inputs.dir }}
