name: "Install Node.js runtime"
description: "Install Node.js runtime and cache node_modules"
inputs:
  dir:
    description: "Working directory for installation"
    required: true
  version:
    description: "Node.js version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.version }}
    - name: Specify cache key
      id: cache
      run: |
        HASH=${{ hashFiles('package-lock.json') }}
        echo "hash=$HASH" >> $GITHUB_OUTPUT
      shell: bash
      working-directory: ${{ inputs.dir }}
    - name: Cache node_modules
      uses: actions/cache@v4
      id: node_modules_cache
      with:
        path: "${{ inputs.dir }}/node_modules"
        key: ${{ runner.os }}-node-modules-${{ steps.cache.hash }}
    - name: Install Dependencies
      if: ${{ steps.node_modules_cache.outputs.cache-hit != 'true' }}
      working-directory: ${{ inputs.dir }}
      run: npm ci
      shell: bash
