name: "Upload docker image to ECR"
description: |
  ディレクトリ dir で Docker イメージをビルドし、Amazon ECR に tag というタグでプッシュします。
inputs:
  aws_region:
    description: "The AWS region"
    default: "ap-northeast-1"
  aws_role:
    description: "The AWS role ARN"
    default: ""
  dir:
    description: "Working directory for docker"
  repository_name:
    description: "Repository name"
  tag:
    description: "Tag to docker image"
  test_commands:
    description: "Test commands for docker image if need"
    default: ""
runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      if: ${{ inputs.aws_role != '' }}
      with:
        role-to-assume: ${{ inputs.aws_role }}
        aws-region: ${{ inputs.aws_region }}
    - name: Login to Amazon ECR
      id: login
      uses: aws-actions/amazon-ecr-login@v2
    - name: Build and tag image for Amazon ECR
      id: build-image
      env:
        ECR: ${{ steps.login.outputs.registry }}
        REPO: ${{ inputs.repository_name }}
        TAG: ${{ inputs.tag }}
      working-directory: ${{ inputs.dir }}
      run: docker build -t $ECR/$REPO:$TAG .
      shell: bash
    - name: Test image
      if: "${{ inputs.test_commands != '' }}"
      env:
        CMD: ${{ inputs.test_commands }}
        ECR: ${{ steps.login.outputs.registry }}
        REPO: ${{ inputs.repository_name }}
        TAG: ${{ inputs.tag }}
      run: docker run --rm --entrypoint= $ECR/$REPO:$TAG $CMD
      shell: bash
    - name: Push image to Amazon ECR
      env:
        ECR: ${{ steps.login.outputs.registry }}
        REPO: ${{ inputs.repository_name }}
        TAG: ${{ inputs.tag }}
      run: docker push $ECR/$REPO:$TAG
      shell: bash
