name: "Run eslint and prettier"
description: "Run eslint and prettier"
inputs:
  dir:
    description: "Working directory for installation"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check by prettier
      run: npm run format
      shell: bash
      working-directory: ${{ inputs.dir }}
    - name: Check by eslint
      run: npm run lint
      shell: bash
      working-directory: ${{ inputs.dir }}
