name: preview-account-destroy
run-name: Destroy preview account for [${{ github.head_ref }}]
on:
  pull_request:
    types:
      - closed
env:
  AWS_REGION: ap-northeast-1
  AWS_ROLE: arn:aws:iam::082954585471:role/rpf-infrastructure-role-dev

jobs:
  infrastructure:
    if: contains(github.event.pull_request.labels.*.name, 'preview-account-deployed')
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Get preview context
        id: context
        uses: ./.github/actions/preview/context
      - name: Remove S3 bucket contents
        uses: ./.github/actions/commons/s3_clear
        with:
          bucket_name: rpf-account-cloudfront-origin-${{ steps.context.outputs.stage }}
      - name: Remove ECR repository and images
        uses: ./.github/actions/commons/ecr_clear_force
        with:
          repository_name: rpf-account-lambda-${{ steps.context.outputs.stage }}
      - uses: ./.github/actions/commons/terraform_install
        with:
          args_init: -backend-config="key=${{ steps.context.outputs.stage }}.tfstate"
          aws_region: ${{ env.AWS_REGION }}
          aws_role: ${{ env.AWS_ROLE }}
          dir: terraform/envs/preview/account
      - name: Terraform destroy
        uses: ./.github/actions/commons/terraform_destroy
        with:
          args_destroy: -var "stage=${{ steps.context.outputs.stage }}"
          dir: terraform/envs/preview/account
          tf_bucket: "rpf-terraform-state-dev"
          tfstate_name: "${{ steps.context.outputs.stage }}.tfstate"
      - uses: ./.github/actions/preview/label_remove
        with:
          name: "preview-account-deployed"

  cleanup:
    needs: [infrastructure]
    if: success() || failure()
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - if: ${{ contains(needs.*.result, 'failure') }}
        uses: ./.github/actions/preview/comment_destroy_failed
      - if: ${{ !contains(needs.*.result, 'failure') }}
        uses: ./.github/actions/preview/comment_destroy
