name: release-log-deploy
run-name: Deploy log for `${{ github.base_ref }}`
on:
  pull_request:
    types:
      - closed
    branches:
      - release/*/log

env:
  AWS_REGION: ap-northeast-1
  AWS_ROLE_ARN_STG: arn:aws:iam::082954585471:role/gha-test-infrastructure-role-dev # TODO 637423178195
  AWS_ROLE_ARN_PROD: arn:aws:iam::082954585471:role/gha-test-infrastructure-role-dev # TODO 315671498329
  DIR_LOG_BACKEND: log/backend
  DIR_LOG_TERRAFORM_STG: terraform/envs/stg/log
  DIR_LOG_TERRAFORM_PROD: terraform/envs/prod/log
  REPO_LOG: gha-test-log-lambda # TODO
  TFSTATE_BUCKET_STG: gha-test-terraform-state-dev # TODO
  TFSTATE_BUCKET_PROD: gha-test-terraform-state-dev # TODO
  TFSTATE_NAME_LOG_STG: gha-test-log-stg.tfstate # TODO
  TFSTATE_NAME_LOG_PROD: gha-test-log-prod.tfstate # TODO

jobs:
  log_backend_deploy_stg:
    if: startsWith(github.base_ref, 'release/stg/log') && github.event.pull_request.merged == true
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get context
        uses: ./.github/actions/context_to_release
        id: context
      - uses: ./.github/actions/commons/lambroll_update_env
        with:
          dir: ${{ env.DIR_LOG_BACKEND }}/lambroll
          repository_name: ${{ env.REPO_LOG }}
          stage: ${{ steps.context.outputs.stage }}
          tag: ${{ steps.context.outputs.sha }}
      - uses: ./.github/actions/commons/lambroll_deploy
        with:
          aws_region: ${{ env.AWS_REGION }}
          aws_role: ${{ env.AWS_ROLE_ARN_STG }}
          dir: ${{ env.DIR_LOG_BACKEND }}/lambroll
          function_names: "A01 A02 A03"
          lambroll_alias: ${{ steps.context.outputs.stage }}
          lambroll_envfile: "${{ steps.context.outputs.stage }}.env"
          tfstate_url: "s3://${{ env.TFSTATE_BUCKET_STG }}/${{ env.TFSTATE_NAME_LOG_STG }}"
      - uses: ./.github/actions/commons/ecr_tagging
        with:
          repository_name: ${{ env.REPO_LOG }}
          tag_origin: ${{ steps.context.outputs.sha }}
          tag_release: ${{ steps.context.outputs.stage }}

  log_backend_deploy_prod:
    if: startsWith(github.base_ref, 'release/prod/log') && github.event.pull_request.merged == true
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get context
        uses: ./.github/actions/context_to_release
        id: context
      - uses: ./.github/actions/commons/lambroll_update_env
        with:
          dir: ${{ env.DIR_LOG_BACKEND }}/lambroll
          repository_name: ${{ env.REPO_LOG }}
          stage: ${{ steps.context.outputs.stage }}
          tag: ${{ steps.context.outputs.sha }}
      - uses: ./.github/actions/commons/lambroll_deploy
        with:
          aws_region: ${{ env.AWS_REGION }}
          aws_role: ${{ env.AWS_ROLE_ARN_PROD }}
          dir: ${{ env.DIR_LOG_BACKEND }}/lambroll
          function_names: "A01 A02 A03"
          lambroll_alias: ${{ steps.context.outputs.stage }}
          lambroll_envfile: "${{ steps.context.outputs.stage }}.env"
          tfstate_url: "s3://${{ env.TFSTATE_BUCKET_PROD }}/${{ env.TFSTATE_NAME_LOG_PROD }}"
      - uses: ./.github/actions/commons/ecr_tagging
        with:
          repository_name: ${{ env.REPO_LOG }}
          tag_origin: ${{ steps.context.outputs.sha }}
          tag_release: ${{ steps.context.outputs.stage }}

  notify_failed:
    needs:
      - log_backend_deploy_stg
      - log_backend_deploy_prod
    if: ${{ failure() && !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        env:
          ACTION_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          ACTOR: ${{ github.actor }}
        with:
          script: |
            const { ACTOR } = process.env
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `@${{ env.ACTOR }} Release task has failed.\nSee ${{ env.ACTION_URL }}`
            })
