name: unused-image-delete
on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  ecrm_delete:
    strategy:
      matrix:
        env:
          - stage: dev
            role: arn:aws:iam::082954585471:role/rpf-infrastructure-role-dev
          - stage: stg
            role: arn:aws:iam::637423178195:role/rpf-infrastructure-role-stg
          - stage: prod
            role: arn:aws:iam::315671498329:role/rpf-infrastructure-role-prod
    env:
      AWS_ROLE_ARN: ${{ matrix.env.role }}
      REGION: ap-northeast-1
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.REGION }}
      - name: Use Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.20.0"
          cache: false
      - name: Install ecrm
        run: go install github.com/fujiwara/ecrm/cmd/ecrm@latest
      - name: Plan by ecrm
        run: ecrm plan
        working-directory: terraform/envs/${{ matrix.env.stage }}
      - name: Delete by ecrm
        run: ecrm delete --force
        working-directory: terraform/envs/${{ matrix.env.stage }}

